routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Task Routes
Route::get('/', 'TasksController@index');
Route::resource('tasks', 'TasksController', ['only' => ['store', 'update', 'destroy']]);
Route::post('tasks/move/{id}', 'TasksController@move')->name('tasks.move');  #update the deadline
Route::post('tasks/restore/{id}', 'TasksController@restore')->name('tasks.restore');  #restore after delete

// Note Routes
Route::get('notes/dialog', 'NotesController@getNoteDialog');
Route::resource('notes', 'NotesController', ['except' => ['index', 'create', 'edit']]);

// User profile Routes
Route::get('user/index', 'UsersController@index');      #to get the profile section
Route::post('user/update', 'UsersController@update');   #update user info
Route::get('user/skin', 'UsersController@updateSkin');  #change the skin[board]

// Authantication Routes
Route::get('authanticate', 'Auth\RegisterController@showRegistrationForm')->name('login');   #sign in|up
Route::post('authanticate/register', 'Auth\RegisterController@register');   #signup
Route::post('authanticate/login', 'Auth\LoginController@login');            #signin
Route::post('authanticate/logout', 'Auth\LoginController@logout');          #logout

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

resources/views/todo/addnote.blade.php
<div class="note_dialog">
    <header>
        <i class="icon ion-compose"></i>
        <input type="text" name="title" id="title" form="note" value="untitled note" placeholder="Enter the note title" required />
        <button type="button" class="btn_close" id="note_close"><i class="icon ion-close"></i></button>
    </header>
    <div class="body">
        <form id="note" action="{{ route('notes.store') }}" data-route="{{ url('notes') }}">
            <textarea name="body" id="note_editor" required></textarea>
            <input type="hidden" id="id" value="0" />
            <div class="save_btn">
                <button type="submit" class="btn btn-primary" id="save_note">Save</button>
            </div>
        </form>
    </div>
    <footer>
        <p>Created at: <time>12:30 PM Monday 10/12/2017</time></p>
        <a href="{{ url('notes') }}" class="delete_note" id="delete_note" title="Delete The Note">
            <i class="ion ion-android-delete"></i>
        </a>
    </footer>
</div>

resources/views/todo/addtask.blade.php
<!-- Add Btn -->
<div class="addbtn">
    <button type="button" class="btn" id="add_task"><i class="icon ion-plus-round"></i></button>
</div>

<!-- Task dialog -->
<div class="dialog hide">
    <div class="header">
        <p class="line">
            <i class="icon ion-star"></i>
            <span>Add New Task</span>
            <button type="button" class="btn_close" id="dialog_close"><i class="icon ion-close"></i></button>
        </p>
    </div>
    <div class="body">
        <form class="form-horizontal" method="post" action="{{ route('tasks.store') }}" data-route="{{ url('tasks') }}">
            <div class="task_editor">
                <textarea id="task_editor" name="body" required></textarea>
            </div>
            <div class="form-group">
                <div class="col-md-2">
                    <label class="control-label" for="date">Date: </label>
                </div>
                <div class="col-md-10">
                    <input type="date" name="date" id="date" class="form-control" value="{{ date("Y-m-d") }}" required />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2">
                    <label class="control-label" for="time">Time: </label>
                </div>
                <div class="col-md-10">
                    <input type="time" name="time" id="time" class="form-control" value="16:40" required />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2">
                    <label class="control-label">Priority: </label>
                </div>
                <div class="col-md-10">
                    <p class="radio-inline">
                        <input type="radio" id="low" name="priority" value="low" checked>
                        <label for="low">Low</label>
                    </p>
                    <p class="radio-inline">
                        <input type="radio" id="mid" name="priority" value="mid">
                        <label for="mid">medium</label>
                    </p>
                    <p class="radio-inline">
                        <input type="radio" id="high" name="priority" value="high">
                        <label for="high">High</label>
                    </p>
                </div>
            </div>

            <input type="hidden" id="id" />
            <div class="footer">
                <button type="submit" id="save_task" class="btn btn-primary">Save</button>
            </div>
        </form>
    </div>
</div>

resources/views/todo/note.blade.php
<li class="note">
    <a href="{{ route('notes.show', $note->id) }}">{{ $note->title }}</a>
</li>

resources/views/todo/task.blade.php
<div class="task {{ $task->priority }}" data-id="{{ $task->id }}" data-move="{{ route('tasks.move', $task->id) }}">

    <div class="info">
        <div class="btns">
            <a href="{{ route('tasks.update', $task->id) }}" class="edit_task" title="Edit Task">
                <i class="ion ion-wrench"></i>
            </a>
            <a href="{{ route('tasks.destroy', $task->id) }}" class="delete_task" title="Delete Task">
                <i class="ion ion-android-delete"></i>
            </a>
        </div>
        <p class="line"><span>deadLine:</span> {{ date('l j F Y h:i A', strtotime($task->deadline)) }}</p>
        <span class="hide" id="timestamp">{{ $task->deadline }}</span>
        <div class="description">{!! $task->body !!}</div>
    </div>

    <div class="restore_message hide">
        restore the deleted task?
        <a href="{{ route('tasks.restore', $task->id) }}">yes</a>
        <button type="button">no</button>
    </div>
</div>